# Generated by Django 4.1.3 on 2023-01-03 09:16

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesparent',
            name='invoice_no',
            field=models.CharField(default=sales.models.invoice_no_generate, max_length=100, primary_key=True, serialize=False),
        ),
    ]
